=== Arioch22/DAW_01/Programacion/NetBeans/Proyectos_NetBeans/Monterroso_Flores_Manuel_Tarea04_LM/public_html/DTD/actividad2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT almazara (clientes)>
<!ATTLIST almazara nombre CDATA #FIXED 'Oleum Est Aurum' CIF CDATA #FIXED 'B12345878'>

<!ELEMENT clientes (cliente)>
<!ELEMENT cliente (contacto,tipo,direccion,telefonos,facturas)*>

<!ATTLIST cliente codigo ID #REQUIRED>
<!ELEMENT contacto (nombre,apellido)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>

<!ELEMENT tipo (particular|empresa)>
<!ELEMENT particular (NIF)>
<!ELEMENT NIF (#PCDATA)>
<!ELEMENT empresa (razon-social,web?,NIF)>
<!ELEMENT razon-social (#PCDATA)>
<!ELEMENT web (#PCDATA)>
<!ELEMENT CIF (#PCDATA)>

<!ELEMENT direccion (via,numero,localidad,provincia,CP)>
<!ELEMENT via (#PCDATA)>
<!ATTLIST via tipo NMTOKEN #REQUIRED>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT CP (#PCDATA)>

<!ELEMENT telefonos (telefono*)>
<!ELEMENT telefono (#PCDATA)>
<!ATTLIST telefono tipo (particular|direccion|rrhh|contabilidad) #REQUIRED>

<!ELEMENT facturas (factura)>
<!ELEMENT factura (forma-pago,fecha-vencimiento,productos,totalizacion)+>
<!ATTLIST factura fecha CDATA #REQUIRED num ID #REQUIRED>

<!ELEMENT forma-pago (#PCDATA)>

<!ELEMENT fecha-vencimiento (#PCDATA)>
<!ATTLIST fecha-vencimiento dias CDATA #REQUIRED>

<!ELEMENT productos (producto)+>
<!ELEMENT producto (nombre,cantidad-unidad,precio,cantidad)>
<!ATTLIST producto codigo ID #REQUIRED>
<!ELEMENT cantidad-unidad (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio moneda NMTOKEN #REQUIRED>
<!ELEMENT cantidad (#PCDATA)>

<!ELEMENT totalizacion (subtotal,iva,total)>
<!ELEMENT subtotal (#PCDATA)>
<!ATTLIST subtotal moneda NMTOKEN #REQUIRED>
<!ELEMENT iva (#PCDATA)>
<!ATTLIST iva tipo CDATA #REQUIRED moneda NMTOKEN #REQUIRED>
<!ELEMENT total (#PCDATA)>
<!ATTLIST total moneda NMTOKEN #REQUIRED>

=== Arioch22/DAW_01/Lenguajes de Marcas/Tarea 04/public_html/DTD/actividad2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<!DOCTYPE almazara SYSTEM "actividad2.dtd">
<almazara nombre="Oleum Est Aurum" CIF="B12345878">
    <clientes>
        <cliente codigo="E1234">
            <contacto>
                <nombre>Manuel</nombre>
                <apellido>Flores</apellido>
            </contacto>
            <tipo>
                <empresa>
                    <razon-social>Restaurante Casa Pepe de la Juderia</razon-social>
                    <web>https://www.restaurantecasapepedelajuderia.com</web>
                    <NIF>B14978647</NIF>
                </empresa>
            </tipo>
            <direccion>
                <via tipo="calle">Romero</via>
                <numero>1</numero>
                <localidad>Córdoba</localidad>
                <provincia>Córdoba</provincia>
                <CP>14003</CP>
            </direccion>
            <telefonos>
                <telefono tipo="rrhh">957520744</telefono>
                <telefono tipo="particular">957777777</telefono>
            </telefonos>
            <facturas>
                <factura num="EMP-22-1234" fecha="19/01/2022">
                    <forma-pago>Efectivo</forma-pago>
                    <fecha-vencimiento dias="28">15/02/2022</fecha-vencimiento>
                    <productos>
                        <producto codigo="PAR-SER-ORO">
                            <nombre>Parqueoliva Serie Oro</nombre>
                            <cantidad-unidad>0,5l/u</cantidad-unidad>
                            <precio moneda="Euro">12,00</precio>
                            <cantidad>30</cantidad>
                        </producto>
                        <producto codigo="RIN-CON-SUB">
                            <nombre>Rincón de la Subbética</nombre>
                            <cantidad-unidad>0,5l/u</cantidad-unidad>
                            <precio moneda="Euro">18,95</precio>
                            <cantidad>12</cantidad>
                        </producto>
                        <producto codigo="JOY-DEL-MON">
                            <nombre>La joya del Monte</nombre>
                            <cantidad-unidad>15l/u</cantidad-unidad>
                            <precio moneda="Euro">69,95</precio>
                            <cantidad>10</cantidad>
                        </producto>
                    </productos>
                    <totalizacion>
                        <subtotal moneda="Euro">1286,90</subtotal>
                        <iva tipo="21" moneda="Euro">270,25</iva>
                        <total moneda="Euro">1557,15</total>
                    </totalizacion>
                </factura>
            </facturas>
        </cliente>
    </clientes>
</almazara>
